export {
  appendGtinCheckDigit,
  appendSsccCheckDigit,
  calculateGs1CheckDigit,
  calculateGtinCheckDigit,
  calculateSsccCheckDigit,
  createGs1DigitalLink,
  createGs1ElementString,
  getGs1AiInfo,
  getSupportedGs1Ais,
  GS1_FNC1_SEPARATOR,
  normalizeGs1DigitalLink,
  parseGs1DigitalLink,
  parseGs1HumanReadable,
  validateGs1DigitalLink,
  validateGs1CheckDigit,
  validateGs1Elements,
  validateGs1ElementString,
  validateGtinCheckDigit,
  validateSsccCheckDigit
} from "./gs1/index.js";
